Team3. Chapter 4
leandevops-ru/leandevops.ru pull request #10
Opened 2023-04-01 16:05 UTC by mchernigin

2023-04-01 16:07 UTC, mchernigin commented
Задача: слить изменения, соблюдая все правила оформления описанные в README и по ссылке там. Файла `MarkdownEditor.md` быть не должно. Весь перевод в `index.md`.

Внимательно прочитайте правила оформления, сейчас, нарушаются почти все.

2023-04-01 16:43 UTC, Mizerael requested changes

2023-04-01 16:43 UTC, Mizerael commented on content/posts/04_friction/MarkdownEditor.md
> +Бережливое производство и идея целенаправленной борьбы с растратами возникли в рамках программы правительства США "Обучение в промышленности" [(1)](https://www.lean.org/search/documents/105.pdf), кот
80 символов нарушено здесь и далее
```suggestion
Бережливое производство и идея целенаправленной борьбы с растратами возникли в рамках программы правительства США "Обучение в промышленности" [(1)](https://www.lean.org/search/documents/105.pdf), которая была разработана для повышения производительности военного производства и преодоления нехватки рабочей силы во время Второй мировой войны. Один из ее наиболее ценных компонентов, "Методы работы" (далее МР), был направлен на сокращение отходов путем непрерывного совершенствования.
```

2023-04-01 16:43 UTC, Mizerael commented on content/posts/04_friction/MarkdownEditor.md
> +>**Трения против расточительства**
отсутствие пробелов после > здесь и далее
```suggestion
>**Трения против расточительства**
```

2023-04-01 16:43 UTC, Mizerael commented on content/posts/04_friction/MarkdownEditor.md
> +## Понимание форм расточительства по методу Оно
заголовок слился с текстом здесь и далее 
```suggestion
## Понимание форм расточительства по методу Оно
```

2023-04-01 16:43 UTC, Mizerael commented on content/posts/04_friction/MarkdownEditor.md
> +>В данный момент Вы можете подумать: "Эй, мне казалось, что эта глава была о
после перевода на русский язык меняйте кавычки в соответствии с REDAME здесь и далее
```suggestion
>В данный момент Вы можете подумать: "Эй, мне казалось, что эта глава была о
```

2023-04-01 16:43 UTC, Mizerael commented on content/posts/04_friction/MarkdownEditor.md
> +>Одним словом, расточительство - это форма разногласий. (В обширном объеме знаний из
все тире пишутся в соответсвии с README как --- здесь и далее
```suggestion
>Одним словом, расточительство - это форма разногласий. (В обширном объеме знаний из
```

2023-04-01 16:43 UTC, Mizerael commented on content/posts/04_friction/MarkdownEditor.md
> +Бережливое производство и идея целенаправленной борьбы с растратами возникли в рамках программы правительства США "Обучение в промышленности" [(1)](https://www.lean.org/search/documents/105.pdf), кот
ссылка указывается после абзаца, в тексте только указатель на ссылку
```suggestion
Бережливое производство и идея целенаправленной борьбы с растратами возникли в рамках программы правительства США "Обучение в промышленности" [(1)](https://www.lean.org/search/documents/105.pdf), которая была разработана для повышения производительности военного производства и преодоления нехватки рабочей силы во время Второй мировой войны. Один из ее наиболее ценных компонентов, "Методы работы" (далее МР), был направлен на сокращение отходов путем непрерывного совершенствования.
```

2023-04-02 18:49 UTC, mchernigin commented on .DS_Store
Удалить...

2023-04-02 18:49 UTC, mchernigin commented on content/posts/04_friction/index.md
> +>В данный момент Вы можете подумать: "Эй, мне казалось, что эта глава была о
Пробел после > в каждой строке

2023-04-02 18:49 UTC, mchernigin commented on content/posts/04_friction/index.md
> +пока вы не выполняли задание?  Что изменило динамику решения задачи настолько,
Нужно сделать замену двух пробелов на один.

2023-04-02 18:49 UTC, mchernigin commented on content/posts/04_friction/index.md
> +>В одной компании такое разделение ответственности привело к длинной цепочке
Тоже пробелы после >

2023-04-02 18:49 UTC, mchernigin commented on content/posts/04_friction/index.md
> +>Каждый, кто зависел от поставщика критически важной инфраструктуры или услуг,
Тоже пробелы после >

2023-04-02 19:09 UTC, mchernigin commented on content/posts/04_friction/index.md
>  что стоит представить многие из его концепций на языке оригинала для того, чтобы
В блоке цитирования, каждая строка должна начинаться с `>`. Образец есть в первой главе.

2023-04-02 19:10 UTC, mchernigin commented on content/posts/04_friction/index.md
>  что стоит представить многие из его концепций на языке оригинала для того, чтобы
И ещё раз отформатировать всё по 80 символов. Есть превышения сейчас.

2023-04-02 21:10 UTC, mchernigin commented on .DS_Store
> Удалить...

Повторить...

2023-04-02 21:12 UTC, mchernigin commented on content/.DS_Store
Задача меняется. Добавить в репозиторий `.gitignore`, который будет игнорировать все .DS_Store файлы.

https://git-scm.com/docs/gitignore

2023-04-08 15:33 UTC, merged