Команды 4 и 5: Добавление перевода 3 главы
leandevops-ru/leandevops.ru pull request #7
Opened 2023-03-24 20:24 UTC by sociopart

2023-03-25 06:32 UTC, Mizerael reviewed
1.  Нарушено разделение на абзацы в нескольких главах
2. В части ##Неправильная оценка сложности экосистемы больше 80 символов в строке

2023-03-26 09:08 UTC, mchernigin requested changes

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +Есть много способов, с помощью которых менеджеры решают проблему лидерства. 
Если здесь начинается новый абзац, должна быть пропущена строка. Если нет, продолжать на той же строке.

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +Найти эффективный метод управления, который был бы устойчив к высокой динамике 
Если здесь начинается новый абзац, должна быть пропущена строка. Если нет, продолжать на той же строке.

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +Рисунок 3.1 <<Наполеон никогда не победит нашу превосходящую армию!>>
После блока другого типа, в данном случае, вставки картинки, необходимо пропустить строку.

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +Все эти трения создают облако неопределенности, которое ставит под угрозу весь 
Если здесь начинается новый абзац, должна быть пропущена строка. Если нет, продолжать на той же строке.

Далее не буду выделять такие такие места в тексте.

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +## Обучение эффективному руководству трудным путем
Перед и после заголовками должна быть одна пустая строка.

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +## Управление через непредсказуемость
Перед и после заголовками должна быть одна пустая строка.

Далее не буду выделять такие места в коде.

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +
2 пустые строки вместо 1

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +
3 пустые строки вместо 1

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +--------------------------------------------------------------
Для разделителя достаточно 3 знаков `---`. Разделитель должен быть окружен пустыми строками.

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> + эффективной , что после объединения Германии в 1871 году была интегрирована в
Пробелы в начале строки.

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +--------------------------------------------------------------
Для разделителя достаточно 3 знаков `---`. Разделитель должен быть окружен пустыми строками.

Далее не буду выделять такие места в коде.

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +
2 пустые строки вместо 1.

Далее не буду выделять такие места в коде.

2023-03-26 09:08 UTC, mchernigin commented on content/posts/03_mission_command/index.md
> +Рисунок 3.4. “...и это то место, где вы найдете цель нашей миссии.>>
Неправильная открывающая кавычка.

2023-03-26 18:55 UTC, sociopart commented
Необходимые правки внесены.

2023-03-26 19:16 UTC, mchernigin approved these changes

2023-03-26 19:19 UTC, Mizerael approved these changes

2023-03-26 19:20 UTC, merged