Глава 5: Риск (Команды 2 и 5)
leandevops-ru/leandevops.ru pull request #8
Opened 2023-03-26 13:40 UTC by aversionq

Перевод главы 5.

2023-04-01 16:15 UTC, mchernigin requested changes

2023-04-01 16:15 UTC, mchernigin commented on content/posts/05_risk/5.md
> +> ### Эксплойт Solar Winds Sunburst.
Заголовки не должны находиться в блоке `>`

2023-04-01 16:15 UTC, mchernigin commented on content/posts/05_risk/5.md
> +>Нарушения безопасности, известные под общим названием взломы SolarWinds, были
После `>` должен быть пробел.

Ошибка повторяется ниже, но я больше указывать на неё не стану.

2023-04-01 16:15 UTC, mchernigin commented on content/posts/05_risk/5.md
> +- Определите и защитите наиболее важные участки, находящиеся в критической
Неправильное оформление списка, смотреть ссылку в README.md: <https://google.github.io/styleguide/docguide/style.html#lists>

Ошибка повторяется ниже, но я больше указывать на неё не стану.

2023-04-01 16:15 UTC, mchernigin commented on content/posts/05_risk/5.md
> +## Переосмысление управления рисками
Пустая строка после заголовка.

2023-04-01 16:15 UTC, mchernigin commented on content/posts/05_risk/5.md
> +обычно , так и ожидаемо, но при этом скрывать ряд серьезных проблем, от
Пробел перед запятой. Попробуйте сделать замену строки " ," на "," во всём файле с помощью find and replace в текстовом редакторе.

2023-04-01 16:15 UTC, mchernigin commented on content/posts/05_risk/5.md
> +отправка обновления в окружение могут скрыть всё - от дефектов и требований к
Минус вместо тире.

2023-04-01 16:15 UTC, mchernigin commented on content/posts/05_risk/5.md
> +    • Где находятся данные, куда они поступают и как они перемещаются по вашей
Неправильное оформление списка вновь: <https://google.github.io/styleguide/docguide/style.html#lists>

2023-04-01 16:15 UTC, mchernigin commented on content/posts/05_risk/5.md
> +• Статистика кода и сборки.
https://google.github.io/styleguide/docguide/style.html#lists

2023-04-01 16:17 UTC, mchernigin commented
Файл `5.md` должен быть `index.md`. Перенести содержимое туда, но сохранить шапку `index.md`.

2023-04-01 16:18 UTC, mchernigin commented
Пожалуйста, читайте README внимательнее.

2023-04-02 21:20 UTC, mchernigin requested changes

2023-04-02 21:20 UTC, mchernigin commented on content/posts/05_risk/index.md
> + ### Эксплойт Solar Winds Sunburst.
Пробел перед заголовком может создать проблемы при генерации сайта.

2023-04-02 21:20 UTC, mchernigin commented on content/posts/05_risk/index.md
> +>
Строка после заголовка должна быть пустой.

2023-04-02 21:20 UTC, mchernigin commented on content/posts/05_risk/index.md
> +вызваны серией уязвимостей в цепочке поставок ИТ. Хакерам удалось подвергнуть
В блоке цитирования, каждая строка начинается с `>`. Пример можно посмотреть в первой главе.

Далее эту ошибку выделять не буду.

2023-04-02 21:20 UTC, mchernigin commented on content/posts/05_risk/index.md
> +    - Определите и защитите наиболее важные участки, находящиеся в критической
Неправильное оформление списка. Должно быть вида:

```md
-   Как можно быстрее разграничьте зоны стабильности и кризиса.
-   Улучшите поток информации везде, где это возможно, чтобы повысить
    осведомленность о ситуации и отслеживать ее.
-   Установите эффективные линии связи с членами команды, чтобы уменьшить 
    путаницу и помочь распределить ресурсы для сдерживания угроз.
-   Постарайтесь стабилизировать ситуацию и перевести ее из состояния хаоса в
    состояние комплексной области.
```

2023-04-08 15:44 UTC, mchernigin approved these changes

2023-04-08 17:54 UTC, Mizerael approved these changes

2023-04-08 18:02 UTC, merged